nome = input('Qual é seu nome?')
dia = input('Digite apenas o DIA em que você nasceu:')
mês = input('Digite apenas o MÊS em que você nasceu:')
ano = input('Digite apenas o ANO em que você nasceu:')
idade = input('Digite a sua idade atual:')
print("Olá, meu nome é", nome+',', "nasci no dia", dia, "de", mês, "do ano de", ano+',', "portanto, atualmente tenho", idade, "anos.")
print("mudando arquivo para commit")